version: '3'

services:
  Nginx:
    hostname: 'Nginx'
    container_name: 'Nginx'
    image: desverreaux/nginx

    volumes:
      - /repo/Desverreaux.com:/var/www/Desverreaux.com
      - /repo/FreshLaravel:/var/www/FreshLaravel
      - /data/Nginx/conf.d:/etc/nginx/conf.d
      - /data/Nginx/logs:/logs
      # the next two lines are required if docker-compose is being called from a virtual box machine with shared folders
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group/

    ports: 
      - "80:80"

    command: tail -f /etc/hosts

    restart: always
