version: '3'

services:
  mysql:
    image: mariadb:10.0.38
    hostname: MariaDB

    container_name: 'MySQL_Datatest'
    ports:
      - "3307:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
            